# Makefile for AmigaOS 68k using VBCC
# Generated by AmigaDevBox setup.ps1
# Vincent Buzzano (ReddoC)

# =============================================================================
# Load environment from .env
# =============================================================================
-include .env

# --- Shell Configuration ---
SHELL = cmd.exe


# --- Configuration ---
TOOLS_DIR = $(VENDOR_DIR)/tools

# Source files (auto-detected)
SRC = $(wildcard $(SRC_DIR)/*.c)
ASM = $(wildcard $(SRC_DIR)/*.s)

# Default program name (can be overridden by make PROGRAM_NAME=...)
EXE = $(DIST_DIR)/$(PROGRAM_NAME)
EXECMDPATH = $(subst /,\,$(EXE))

# Generated files
OBJS = $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(SRC))
ASM_FILES = $(patsubst $(SRC_DIR)/%.c,$(ASM_DIR)/%.asm,$(SRC))
ASM_OBJS = $(patsubst $(SRC_DIR)/%.s,$(OBJ_DIR)/%.o,$(ASM))
ALL_OBJS = $(OBJS) $(ASM_OBJS)

# Compiler and Linker
CC = vc
LINK = vc

# VBCC Target
TARGET=aos68k 
C_INCL_VBCC = $(VBCC)/targets/m68k-amigaos/include

# NDK 3.9
C_INCL_NDK39 = $(NDK39)/Include/include_h

# --- Includes ---	
#C_INCL_ALL = -I$(SRC_DIR) -I$(INCLUDE_DIR)  -I$(C_INCL_NDK39) -I$(C_INCL_NM)
C_INCL_ALL = -I$(C_INCL_VBCC) -I$(C_INCL_NDK39) -I$(SRC_DIR) -I$(INCLUDE_DIR) -I$(NEWMOUSE_INC)

# --- Optimization ---
# List of all supported CPUs
CPU := 68080

# --- Compiler and Linker Flags ---
# Optional user flags (e.g., make EXTRA_CFLAGS=-DDISABLE_LOGGING)
EXTRA_CFLAGS ?=
AMIGA_FLAGS = +$(TARGET) -nostdlib

# Release: optimize for speed, 68080 specific
# -O3: all optimizations (single file, no cross-module needed)
# -speed: prefer speed over size (hot polling loop)
# -sc: small code model (16-bit PC-relative calls)
# -sd: small data model (16-bit A4-relative data access)
# -schedule: instruction scheduling for 68080 dual-pipe
# -cpu=68080: use 68080 instructions
# Note: -fpu removed (no floating point in this driver)
#CFLAGS = -O3 -speed -sc -schedule $(C_INCL_ALL) $(EXTRA_CFLAGS) -cpu=$(CPU)
#CFLAGS = -O3 -size -sc -sd -schedule $(C_INCL_ALL) $(EXTRA_CFLAGS) -cpu=$(CPU)

# Build mode (dev, debug or release)
MODE ?= dev

# C flags
ifeq ($(MODE),release)
    # Release: optimize size, strip debug, remove LOG_Debug
    CFLAGS = -O3 -speed -sc -schedule -DRELEASE $(C_INCL_ALL) $(EXTRA_CFLAGS) -cpu=$(CPU)
else
    # Dev: same optimization but with debug symbols
    CFLAGS = -O3 -speed -sc -schedule $(C_INCL_ALL) $(EXTRA_CFLAGS) -cpu=$(CPU)
endif


# Linker flags
LDFLAGS =


# --- Build Rules ---
# Default target
all: dirs build

dirs:
	@if not exist "$(BUILD_DIR)" mkdir "$(BUILD_DIR)"
	@if not exist "$(OBJ_DIR)" mkdir "$(OBJ_DIR)"
	@if not exist "$(ASM_DIR)" mkdir "$(ASM_DIR)"
	@if not exist "$(DIST_DIR)" mkdir "$(DIST_DIR)"


build: $(EXE) #$(ASM_FILES)
rebuild: clean build

release:
	$(MAKE) MODE=release rebuild

# Create directories if they don't exist
$(BUILD_DIR) $(DIST_DIR) $(OBJ_DIR) $(ASM_DIR):
	@if not exist "$@" mkdir "$@"

# Link the executable
$(EXE): $(ALL_OBJS) | $(DIST_DIR)
	$(CC) $(CFLAGS) $(AMIGA_FLAGS) $(LDFLAGS) -o $@ $^

# Compile sources (src/*.c)
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	$(CC) $(CFLAGS) $(AMIGA_FLAGS) -c -o $@ $<

# Generate assembly files from .c sources
$(ASM_DIR)/%.asm: $(SRC_DIR)/%.c | $(ASM_DIR)
	$(CC) $(CFLAGS) $(AMIGA_FLAGS) -S -o=$@ $<

# Assemble .s files
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.s | $(OBJ_DIR)
	$(VBCC_PATH)/bin/vasmm68k_mot -Fhunk -o $@ $<

# --- Housekeeping ---
clean:
	@if exist "$(ASM_DIR)\*" del /f /q "$(ASM_DIR)\*"
	@if exist "$(OBJ_DIR)\*" del /f /q "$(OBJ_DIR)\*"
	@if exist "$(DIST_DIR)\*" del /f /q "$(DIST_DIR)\*"
	@echo Cleaned build files while preserving directory structure

upload: $(EXE)
	@echo ------------------------------------------------------------------
	@echo ApolloExplorer Upload
	@$(ACP) $(EXECMDPATH) "$(APOLLO_V4_HOST)"
#	@$(ACP) $(GUIDEPATH) "$(APOLLO_V4_HOST)"
#	@$(ACP) $(INSTALLPATH) "$(APOLLO_V4_HOST)"
	@$(ACP) $(GDB) "$(APOLLO_V4_HOST)"
	@echo bgdbserver $(EXE_NAME) > $(EXECMDPATH)_Debug
	@$(ACP) $(EXECMDPATH)_Debug "$(APOLLO_V4_HOST)"

help:
	@echo Available targets:
	@echo   all        - Build (default)
	@echo   build      - Build the project
	@echo   rebuild    - Clean and build
	@echo   clean      - Remove build files
	@echo   upload     - Upload to Vampire V4

# Phony targets
.PHONY: all help clean upload build rebuild
