# ============================================================================
# Environment Files Generation
# ============================================================================

function Generate-DotEnvFile {
    $envPath = Join-Path $BaseDir ".env"
    $state = Load-State
    
    $lines = @(
        "# Generated by setup.ps1 - DO NOT EDIT"
        "# Re-run 'setup.ps1 env update' to regenerate"
        "# $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
        ""
        "# Project Settings"
    )
    
    # Project settings from merged config
    if ($Config.Project) {

        
        $lines += "PROGRAM_NAME=$($Config.Project.Name)"
        $lines += "PROGRAM_AUTHOR=$($Config.Project.Author)"
        $lines += "PROGRAM_VERSION=$($Config.Project.Version)"
        $lines += "PROGRAM_DATE=$($Config.Project.VersionDate)"
        $lines += "PROGRAM_DESCRIPTION=$($Config.Project.Description)"
        $lines += "PROGRAM_DESC_SHORT=$($Config.Project.DescShort)"
        
        if ($Config.Build.EXE_NAME) {
            $lines += "PROGRAM_EXE_NAME=$($Config.Build.EXE_NAME)"
        } else {
            $lines += "PROGRAM_EXE_NAME=$($Config.Project.Name)"
        }

        if ($Config.Build.DefaultCPU) {
            $lines += "CPU=$($Config.Build.DefaultCPU)"
        }
        if ($Config.Build.DefaultFPU) {
            $lines += "FPU=$($Config.Build.DefaultFPU)"
        }
    }
    
    $lines += ""
    $lines += "# Project Paths"
    
    # Paths from merged config
    if ($Config.Paths) {
        foreach ($key in $Config.Paths.Keys) {
            $value = $Config.Paths[$key]
            $envKey = ($key -creplace '([A-Z])', '_$1').ToUpper().TrimStart('_')
            $lines += "$envKey=$value"
        }
    }
    
    $lines += ""
    $lines += "# Package Paths"
    
    foreach ($pkgName in $state.packages.Keys) {
        $pkg = $state.packages[$pkgName]
        if ($pkg.envs) {
            foreach ($envName in $pkg.envs.Keys) {
                $envValue = $pkg.envs[$envName]
                $lines += "$envName=$envValue"
            }
        }
    }
    
    # Custom envs from config (Envs section)
    if ($Config.Envs -and $Config.Envs.Count -gt 0) {
        $lines += ""
        $lines += "# Custom Variables"
        foreach ($key in $Config.Envs.Keys) {
            $value = $Config.Envs[$key]
            $lines += "$key=$value"
        }
    }
    
    $lines -join "`n" | Out-File $envPath -Encoding UTF8 -NoNewline
    Write-Success "Generated .env"
}

function Generate-AllEnvFiles {
    Generate-DotEnvFile
}

# ============================================================================
# Env Commands
# ============================================================================

function Show-EnvList {
    Write-Host ""
    Write-Host "Environment Variables:" -ForegroundColor Cyan
    Write-Host ""
    
    $state = Load-State
    
    # Project settings
    Write-Host "  [Project Settings]" -ForegroundColor Yellow
    if ($Config.Project) {
        if ($Config.Project.Name) {
            Write-Host "    PROGRAM_NAME = $($Config.Project.Name)" -ForegroundColor White
        }
        if ($Config.Project.DefaultCPU) {
            Write-Host "    DEFAULT_CPU = $($Config.Project.DefaultCPU)" -ForegroundColor White
        }
        if ($Config.Project.DefaultFPU) {
            Write-Host "    DEFAULT_FPU = $($Config.Project.DefaultFPU)" -ForegroundColor White
        }
        if ($Config.Project.Version) {
            Write-Host "    VERSION = $($Config.Project.Version)" -ForegroundColor White
        }
    }
    
    # Paths
    Write-Host ""
    Write-Host "  [Project Paths]" -ForegroundColor Yellow
    if ($Config.Paths) {
        foreach ($key in $Config.Paths.Keys) {
            $value = $Config.Paths[$key]
            $envKey = ($key -creplace '([A-Z])', '_$1').ToUpper().TrimStart('_')
            Write-Host "    $envKey = $value" -ForegroundColor White
        }
    }
    
    # Package envs
    Write-Host ""
    Write-Host "  [Package Paths]" -ForegroundColor Yellow
    foreach ($pkgName in $state.packages.Keys) {
        $pkg = $state.packages[$pkgName]
        if ($pkg.envs -and $pkg.envs.Count -gt 0) {
            foreach ($envName in $pkg.envs.Keys) {
                $envValue = $pkg.envs[$envName]
                Write-Host "    $envName = $envValue" -ForegroundColor White -NoNewline
                Write-Host " ($pkgName)" -ForegroundColor DarkGray
            }
        }
    }
    
    # Custom envs from config
    if ($Config.Envs -and $Config.Envs.Count -gt 0) {
        Write-Host ""
        Write-Host "  [Custom Variables]" -ForegroundColor Yellow
        foreach ($key in $Config.Envs.Keys) {
            $value = $Config.Envs[$key]
            Write-Host "    $key = $value" -ForegroundColor White
        }
    }
    
    Write-Host ""
}
